#:schema https://raw.githubusercontent.com/YunoHost/apps/main/schemas/manifest.v2.schema.json

packaging_format = 2

id = "litechat"
name = "LiteChat"
description.en = "Local first AI chat app for your browser"
description.fr = "Application locale de chat avec IA pour votre navigateur"

version = "0.2.0~ynh2"

maintainers = ["eric_G"]

[upstream]
license = "MIT"
demo = "https://litechat.dev/"
admindoc = "https://dbuild.dev/blog/projects-litechat-litechat-un-chat-ia-local-first-auto-hebergeable-sur-un-server-http/"
code = "https://github.com/DimitriGilbert/LiteChat"

[integration]
yunohost = ">= 12.0.9"
helpers_version = "2.1"
architectures = "all"
multi_instance = true

ldap = false
sso = false

disk = "50M"
ram.build = "60M"
ram.runtime = "30M"

[install]
    [install.domain]
    type = "domain"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]

    [resources.sources]

    [resources.sources.main]
    in_subdir = false
    url = "https://github.com/DimitriGilbert/LiteChat/releases/download/0.2.0/0.2.0.zip"
    sha256 = "e566a318592863b08ec51608a6dfb41189692dd0c5390e988e499fff00397b66"

    autoupdate.strategy = "latest_github_release"
    autoupdate.asset = ".*\.zip"

    [resources.system_user]

    [resources.install_dir]
    group = "www-data:r-x"

    [resources.permissions]
    main.url = "/"
